---
- name: MariaDB database
  hosts: maxscale
  remote_user: root
  become: true
  become_user: root
  gather_facts: true
  vars_files:
    - playbook_vars.yml
  tasks:
    - name: install needed dependencies
      apt:
        pkg:
          - wget
          - apt-transport-https
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: get MariaDB repository helper script
      shell: wget https://dlm.mariadb.com/enterprise-release-helpers/mariadb_es_repo_setup
      register: repo_check
    - name: modify repo_setup
      shell: chmod +x mariadb_es_repo_setup
    - name: apply customer download token
      shell: sudo ./mariadb_es_repo_setup --token="{{ download_token }}" --apply --skip-server --skip-tools --mariadb-maxscale-version="{{ dbVersion }}"
    - name: install mariadb for CentOS/Debian/RHEL
      yum:
        name: 
          - maxscale
        #update_cache: yes
        state: present
      when: ansible_facts['distribution'] == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: install mariadb for Ubuntu
      apt:
        pkg:
          - maxscale
        state: present
        #update_cache: yes
        install_recommends: yes
        #cache_valid_time: 7200
      when: ansible_facts['distribution'] == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Start maxscale service
      service:
              name: maxscale
              enabled: yes
              state: started


