---
- name: MariaDB database
  hosts: dbservers
  remote_user: root
  become: true
  become_user: root
  gather_facts: true
  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      apt: name=python3-mysqldb state=present
  tasks:
    - name: install needed dependencies
      apt:
        pkg:
          - wget
          - apt-transport-https
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: get MariaDB repository helper script
      shell: wget https://dlm.mariadb.com/enterprise-release-helpers/mariadb_es_repo_setup
      register: repo_check
    - name: modify repo_setup
      shell: chmod +x mariadb_es_repo_setup
    - name: apply customer download token
      shell: sudo ./mariadb_es_repo_setup --token="{{ download_token }}" --apply --mariadb-server-version="{{ dbVersion }}"
    - name: install mariadb for CentOS/Debian/RHEL
      yum:
        name: 
          - mariadb-server
          - mariadb-client
          - mariadb-backup
          - python3-PyMySQL
        enablerepo: mariadb-repo
        #state: latest
        update_cache: yes
      when: ansible_facts['distribution'] == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: install mariadb for Ubuntu
      apt:
        pkg:
          - mariadb-server
          - mariadb-client
          - mariadb-backup
        state: present
        #update_cache: yes
        install_recommends: yes
        #cache_valid_time: 7200
      when: ansible_facts['distribution'] == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Start mariadb service
      service:
              name: mariadb
              enabled: yes
              state: started
    - name: enable mariadb service
      service:
        name: mariadb
        enabled: yes
    - name: reset bind_address
      command: sed -i 's/bind-address/#bind-address/g' /etc/mysql/mariadb.conf.d/50-server.cnf
    - name: Generate server_id for the DB Servers
      shell: cat /proc/sys/kernel/random/uuid | awk -F- '/[0-9]/ {print $1}' | grep -Eo '[0-9][0-9]' | grep -v '^[0;]' | head -1
      register: mysql_server_id
    - name: Copy my.cnf template files
      template:
        src: ini_cnf_template
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
        owner: mysql
        group: mysql
        mode: 0600
    - name: Restart mariadb service
      service:
              name: mariadb
              enabled: yes
              state: restarted
    - name: create replication user
      command: |
        mysql -ABNe "GRANT REPLICATION SLAVE,REPLICATION CLIENT ON *.* TO '{{ repl_user }}'@'%' IDENTIFIED BY '{{ repl_pwd }}';"
    - name: flush privs table
      command: "mysql -Ae 'flush privileges;'"
- hosts: dbservers[0]
  remote_user: root
  become: true
  gather_facts: true
  vars_files:
    - playbook_vars.yml
  tasks:
    - set_fact:
        master_ip: "{{ ansible_default_ipv4.address }}"
        cacheable: yes
    - name: get master log file
      shell: "mysql -ABNe 'show master status;' |  cut -f 1"
      register: master_log_file
    - name: get master log pos
      shell: "mysql -ABNe 'show master status;' |  cut -f 2"
      register: master_log_pos
- hosts: dbservers[1:]
  remote_user: root
  become: true
  gather_facts: true
  vars_files:
    - playbook_vars.yml
  vars:
    master_host: "{{ hostvars['master']['ansible_facts']['master_ip'] }}"
    master_logfile: "{{ hostvars['master']['master_log_file']['stdout'] }}"
    master_logpos: "{{ hostvars['master']['master_log_pos']['stdout'] }}"
  tasks:
    - name: Setup replication
      command: |
        mysql -ABNe "CHANGE MASTER TO MASTER_HOST='{{ master_host }}',MASTER_USER='{{ repl_user | quote }}',MASTER_PASSWORD={{ repl_pwd | quote }},MASTER_CONNECT_RETRY=10,MASTER_LOG_FILE='"{{ master_logfile  }}"',MASTER_LOG_POS={{ master_logpos }};"
    - name: start replication slave thread
      command: mysql -e "START SLAVE;"
    - name: set replica to read_only
      command: mysql -e "SET GLOBAL read_only=ON;"

 
